### ISSUE TITLE
Extension Fails to Run Local Ollama Model and Gets Stuck on "Loading...

### ISSUE THREAD

**Issue by ulysses-potiguara** [zachatrocity/ulauncher-ollama#1]
Hi there.

The extension appears unable to run the model from the local Ollama instance. It remains stuck displaying "Loading..." indefinitely.

OS: ElementaryOS 7.1 Horus
Ubuntu 22.04.5 LTS
Ulauncher v5.15.7

Appreciate the help

![ollama ulauncher](https://github.com/user-attachments/assets/6dcfc443-e9f3-4fe8-a7f5-eaa9bbb3dbea)

**Comment by itskavin** [comment]
hey,
I found a solution you need to check:
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux

follow those steps and It should work as expected.

**Comment by zachatrocity** [comment]
Thanks for sharing @kavinthangavel!

Please reopen @ulysses-potiguara if you're still seeing issues.
